Name-2501437_Gritika_Shrestha

4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.

Problem - 1: Array Creation:

In [1]:
import numpy as np
import time

Problem - 1: Array Creation:

In [4]:
# 1) Empty 2x2 array
import numpy as np
arr = np.empty((2,2))
print(arr)


# 2) All ones array 4x2
arr = np.ones((4,2))
print(arr)

# 3) Array filled with a value
arr = np.full((4,2), 8)
print(arr)

# 4) Zeros array same shape as a given array
arr = [[1,2], [3,4]]
arr2 = np.zeros_like(arr)
print(arr2)

# 5) Ones array same shape as a given array
arr = [[1,2], [3,4]]
arr2 = np.ones_like(arr)
print(arr2)

# 6) Convert list to numpy array
new_list = [1,2,3,4]
arr = np.array(new_list)
print(arr)

[[5.47245346e-315 0.00000000e+000]
 [6.81856853e-091 1.52063837e-047]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[8 8]
 [8 8]
 [8 8]
 [8 8]]
[[0 0]
 [0 0]]
[[1 1]
 [1 1]]
[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [5]:
# 1) Array from 10 to 49
arr = np.arange(10, 50)
print(arr)

# 2) 3x3 matrix 0 to 8
arr=np.arange(0,9)
reshape_arr=arr.reshape(3,3)
print(reshape_arr)

# 3) Identity matrix 3x3
arr= np.eye(3)
print(arr)

# 4) Random array of size 30 + mean
import random as random
arr = np.random.random(30)
print(arr)
mean= np.mean(arr)
print(f"mean is {mean}")

# 5) 10x10 random array min, max
arr= np.random.random((10,10))
max= np.max(arr)
min=np.min(arr)
print(f"max is {max} and min is {min}")

# 6) Zero array size 10, replace 5th element with 1
arr=np.zeros(10)
print(arr)
arr[4]=1
print(arr)

# 7) Reverse an array
arr=[1, 2, 0, 0, 4, 0]
reverse = np.flip(arr)
print(reverse)

# 8) Border 1s, inside 0s (example 5x5)
n,m = 5, 5
arr = np.zeros((n,m))
arr[0, :] = 1
arr[-1, :] = 1
arr[:, 0] = 1
arr[:, -1] = 1
print(arr)


# 9) 8x8 checkerboard
checkboard=np.ones((8,8))
checkboard[1::2, ::2]=0
checkboard[::2, 1::2]=0
print(checkboard)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.89635377 0.5048051  0.1595065  0.62880862 0.19855648 0.65941867
 0.96443054 0.94121301 0.25317147 0.21397203 0.22262976 0.2849505
 0.03698633 0.68389753 0.35740051 0.79735279 0.94567252 0.39191182
 0.02004041 0.76280544 0.12067537 0.39877822 0.53847921 0.60711778
 0.11684993 0.47162111 0.29991951 0.45952202 0.00371304 0.76049719]
mean is 0.4567019064592301
max is 0.988259555334497 and min is 0.004856488355503896
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0 4 0 0 2 1]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


Problem - 3: Array Operations:

In [6]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print(np.add(x,y))
print(np.add(v,w))
print(np.subtract(x,y))
print(np.subtract(v,w))
print((x,y)*2)
print((v,w)*5)
print(np.square(x))
print(np.square(y))
print(np.square(v))
print(np.square(w))
print(np.dot(v,w))
print(np.dot(x,v))
print(np.dot(x,y))
print(np.concatenate((x,y), axis=0))#row concatenation
#v anw w reshape
v=v.reshape(2,1)
w=w.reshape(2,1)
print(np.concatenate((v,w), axis=1))#column concatenation
print(np.concatenate((x,v), axis =1))
#print(np.concatenate((x,v), axis=0))# same as above different dimension

# 7) Try concatenating x and v
try:
    bad = np.concatenate((x, v))
except Exception as e:
    print("\n7) Error concatenating x and v:\n", e)
    print("Reason: x is 2D with shape", x.shape,
          "but v is 1D with shape", v.shape)


[[ 6  8]
 [10 13]]
[20 22]
[[-4 -4]
 [-4 -3]]
[-2 -2]
(array([[1, 2],
       [3, 5]]), array([[5, 6],
       [7, 8]]), array([[1, 2],
       [3, 5]]), array([[5, 6],
       [7, 8]]))
(array([ 9, 10]), array([11, 12]), array([ 9, 10]), array([11, 12]), array([ 9, 10]), array([11, 12]), array([ 9, 10]), array([11, 12]), array([ 9, 10]), array([11, 12]))
[[ 1  4]
 [ 9 25]]
[[25 36]
 [49 64]]
[ 81 100]
[121 144]
219
[29 77]
[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]
[[ 1  2  9]
 [ 3  5 10]]

7) Error concatenating x and v:
 all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 1
Reason: x is 2D with shape (2, 2) but v is 1D with shape (2, 1)


Problem - 4: Matrix Operations:

In [7]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
A_inverse=np.linalg.inv(A)
print(np.dot(A, A_inverse))
print(np.dot(A,B))
print(np.dot(B,A))
AB = np.dot(A,B)
at= np.transpose(A)
bt= np.transpose(B)
print(np.dot(at,bt))




[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
[[23 13]
 [51 29]]
[[36 44]
 [13 16]]
[[36 13]
 [44 16]]


In [8]:
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])
A_inverse = np.linalg.inv(A)
X = np.dot(A_inverse, B)
print(X)

[ 2.  1. -2.]


4.2 Experiment: How Fast is Numpy?

Experiment: Python Lists vs NumPy Speed

Matrix Multiplication Test (1000×1000)

In [9]:
import timeit
list1 = list(range(1000000))
list2 = list(range(1000000))


In [10]:
from timeit import timeit
def add_python(Z1, Z2):
  return [z1 + z2 for z1, z2 in zip(Z1, Z2)]
def add_numpy(Z1, Z2):
  return np.add(Z1, Z2)
Z1 = random.sample(range(1000000), 10000)
Z2 = random.sample(range(1000000), 10000)
python_time = timeit("add_python(Z1,Z2)", globals=globals(), number=100)
numpy_time = timeit("add_numpy(Z1,Z2)", globals=globals(), number=100)
print(f"Pure Python addition: {python_time:.2f} s per loop")
print(f"Numpy addition: {numpy_time:.2f} s per loop")

Pure Python addition: 0.07 s per loop
Numpy addition: 0.13 s per loop


In [11]:
from timeit import timeit
def mul_python(Z1, Z2):
  return [z1 * z2 for z1, z2 in zip(Z1, Z2)]
def mul_numpy(Z1, Z2):
  return np.multiply(Z1, Z2)
Z1 = random.sample(range(1000000), 10000)
Z2 = random.sample(range(1000000), 10000)
python_time = timeit("mul_python(Z1,Z2)", globals=globals(), number=100)
numpy_time = timeit("mul_numpy(Z1,Z2)", globals=globals(), number=100)
print(f"Pure Python multiplication: {python_time:.2f} s per loop")
print(f"Numpy multiplication: {numpy_time:.2f} s per loop")

Pure Python multiplication: 0.05 s per loop
Numpy multiplication: 0.08 s per loop


In [12]:
from timeit import timeit
def dot_python(Z1, Z2):
  return sum(z1 * z2 for z1, z2 in zip(Z1, Z2))
def dot_numpy(Z1, Z2):
  return np.dot(Z1, Z2)
Z1 = random.sample(range(1000000), 10000)
Z2 = random.sample(range(1000000), 10000)
python_time = timeit("dot_python(Z1,Z2)", globals=globals(), number=100)
numpy_time = timeit("dot_numpy(Z1,Z2)", globals=globals(), number=100)
print(f"Pure Python dot product: {python_time:.2f} s per loop")
print(f"Numpy dot product: {numpy_time:.2f} s per loop")

Pure Python dot product: 0.06 s per loop
Numpy dot product: 0.11 s per loop


In [13]:
from timeit import timeit
matrix1 = np.random.random((1000, 1000))
matrix2 = np.random.random((1000, 1000))
list1 = matrix1.tolist()
list2 = matrix2.tolist()
def matrix_python(list1, list2):
  list2_T = list(zip(*list2))
  return [[sum(a*b for a,b in zip(list1_row,list2_col)) for list2_col in list2_T] for list1_row in list1]
def matrix_numpy(matrix1, matrix2):
  return np.matmul(matrix1, matrix2)
#Z1 = random.sample(range(1000000), 10000)
#Z2 = random.sample(range(1000000), 10000)
python_time = timeit("matrix_python(list1,list2)", globals=globals(), number=1)
numpy_time = timeit("matrix_numpy(matrix1,matrix2)", globals=globals(), number=1)
print(f"Pure Python matrix multiplication: {python_time:.2f} s per loop")
print(f"Numpy matrix multiplication: {numpy_time:.2f} s per loop")

Pure Python matrix multiplication: 58.24 s per loop
Numpy matrix multiplication: 0.05 s per loop
